#define		SIDENTIFICADOR 2	
#define		SPONTOEVIRGULA 3
#define		SDOISPONTOS	5
#define		SINTEGER	7
#define		SCHAR	8
#define   SFLOAT 9
#define   SDOUBLE 10
#define   SSHORT 11
#define   SLONG 12
#define   SUNSIGNED 13
#define   SSIGNED 14
#define   SABRECHAVES 15
#define   SFECHACHAVES 16
#define   SABRECOLCHETES 17
#define   SFECHACOLCHETES 18
#define   SSTRUCT 19
#define   SUNION 20
#define   SENUM 21
#define   SVOID 22
#define   SAUTO 23
#define   SBREAK 24
#define   SCONST 25
#define   SCONTINUE 26
#define   SDEFAULT 27
#define   SDO 28
#define   SEXTERN 29
#define   SFOR 30
#define   SGOTO 31
#define   SINLINE 32
#define   SREGISTER 33
#define   SRESTRICT 34
#define   SRETURN 35
#define   SSIZEOF 36
#define   SSTATIC 37
#define   SSWITCH 38
#define   STYPEDEF 39
#define   SVOLATILE 40
#define   SWHILE 41
#define	  SABREPAR 42	
#define		SFECHAPAR	43
#define		SATRIBUICAO	44
#define   SDECREMENTACAO 45 
#define		SVIRGULA 46
#define		SBEGIN 47
#define		SIF 48
#define		SELSE	49
#define		SINTEIRO 50	
#define		SMAIORQUE	51
#define   SMENORQUE 57
#define   SMAIORIGUAL 58
#define   SMENORIGUAL 59
#define		SPONTO 52
#define		SMAIS	53
#define		SDIVI	54
#define   SMULTIPLICACAO 55
#define   SMENOS 56
